### PR TITLE
Modifies some function and variable ordering so they're alphabetized

### PR DESCRIPTION
**Pull request by amuller26**
Alphabetizes everything that can be listed in alphabetical order.

### CODE REVIEW

**Comment by amuller26** [comment]
Some functions and variables I didn't alphabetize because I wasn't sure if there was a specific reason why they are grouped how they are, like everything in the `Sugarsape __init__`.

**Review by colinhanrahan — APPROVED** [review]
Looks good! I have nitpicks and no useful feedback.

**Comment by nkremerh** [comment]
Resolved merge conflicts. @amuller26, please double check I did not accidentally overwrite any of your changes by comparing this to your local version.

**Comment by amuller26** [comment]
I finished modifying all files, and I am pretty sure all of the conflicts are now resolved and merged.

**Comment by nkremerh** [comment]
Just kidding. Now the merge conflicts should be resolved. I accidentally introduced a bug into the master branch which broke this PR for a bit. All fixed. Ready for review.

**Comment by amuller26** [comment]
Fixed.

**Pull request merged**
