### PR TITLE
Adds multiple debug modes to the simulation

### PR DESCRIPTION
**Pull request by WillemHueffed**
Adds debug mode options to README
Modifies config file debug mode option from boolean to string

### CODE REVIEW

**Comment by WillemHueffed** [comment]
1. Done 
2. Updated - config file is now an array where multiple debug modes can be entered as CSVs. Control structure conditions now use if...in

**Comment by WillemHueffed** [comment]
Third tries the charm?

**Comment by nkremerh** [comment]
Final pieces:

1. Add some validation to verifyConfiguration in sugarscape.py to handle a few cases:
    a. Both all and none being specified should throw an error message and abort the program.
    b. If all is specified with subcomponents (e.g. [all, agent, disease]), the list should be condensed to just [all].
    c. If a subcomponent is specified which does not exist, throw an error message and abort the program.
2. Set the default debugMode to ["all"] in config.json.
3. The default debugMode in sugarscape.py (line 755) should be ["none"] within a list, correct?

Otherwise, this works perfectly. Good work.

**Comment by WillemHueffed** [comment]
1. I used sets to keep the code relatively clean (saves some weird O(n^2) wonkiness) -  hope that's okay
2./3. Thanks for catching those!

**Review by nkremerh — APPROVED** [review]

**Pull request merged**
