### PR TITLE
adds universal basic income

### PR DESCRIPTION
**Pull request by lucas-vorkpork**
@will can you peer review?

### CODE REVIEW

**Comment by lucas-vorkpork** [comment]
Update: Don't pull, an error popped up in the process of squashing commits. Working on it

**Review by will — APPROVED** [review]
Lgtm

**Comment by lucas-vorkpork** [comment]
Yeah, sorry about that, my mistake. I fixed up the error, too. @marishuman could you take a look at it?

**Review by nkremerh — CHANGES_REQUESTED** [review]
It looks like the cause of the spiking metabolism is rampant disease (which increases agent metabolism). When comparing the same seed with and without UBI, the society without UBI overcomes disease and reaches a mean metabolism ~1.0 whereas the UBI population doesn't shake off disease and sees a skyrocketing metabolism (and the population dies out). Something to investigate.

**Review by nkremerh — APPROVED** [review]

**Pull request merged**
