### PR TITLE
Adds movement as separate mechanic

### PR DESCRIPTION
**Pull request by asipes33**

### CODE REVIEW

**Review by nkremerh — CHANGES_REQUESTED** [review]
There seem to be a number of artifacts from a merge conflict (the <<< HEAD, >>>, and === lines). Give this another pass to remove all those (and be sure the lines kept after the merge conflict are the ones you want to push). Please also take a pass to remove any comments and commented out code that should be removed (like old debugging messages).

**Comment by asipes33** [comment]
> There seem to be a number of artifacts from a merge conflict (the <<< HEAD, >>>, and === lines). Give this another pass to remove all those (and be sure the lines kept after the merge conflict are the ones you want to push). Please also take a pass to remove any comments and commented out code that should be removed (like old debugging messages).

I meant to take all those out before the meeting we had, my apologies. I'll get this taken care of before the beginning of next week.

**Comment by nkremerh** [comment]
It looks like this is close to being ready to merge, but there are still issues with agent.py removing lines that were added recently in the commit history and having some merge conflict artifacts left over.

**Comment by nkremerh** [comment]
This PR needs to be rebased onto the latest changes and updated accordingly re. an agent having a movementModifier value which tracks how their contracted diseases impact their movement capabilities. Look to visionModifier for an example usage.

This PR is close. Let's close in on getting it ready for merging.

**Comment by nkremerh** [comment]
@asipes33 @WillemHueffed Pushed this feature based on the highlights of this PR. Closing this PR, but please double check my work and open another PR if fixes are needed.

**Pull request closed without merging**
